import {act,cleanup,fireEvent,render,screen,within} from '@testing-library/react';
import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {AssetSearch} from './AssetSearch';
import {AssetScopeChips} from './AssetScopeChips';
import {assetSuggestions,readAssetSearchRecents,writeAssetSearchRecents,type AssetSuggestion} from './assetSearchModel';
import {assetSearchKey,groupAssetSuggestions,rememberAssetSearch,type AssetSearchIdentity} from '../src/assets/assetSearch';
import {PRIVACY_MODE_KEY} from './privacyMode';
import type {LibraryArtist} from './artistsModel';
const mocks=vi.hoisted(()=>({api:vi.fn()}));
vi.mock('./transport',()=>({api:mocks.api}));
vi.mock('./media',()=>({loadThumbnail:vi.fn(async(asset)=>asset)}));
const artist:LibraryArtist={id:'artist',label:'서리 작가',keys:[],assetCount:4,recentCount:0,pinned:false,hidden:false,main:true,coverAssetIds:['art-cover']};
const tree={adopted:true,libraryId:'library',epoch:3,code:'',albums:[{id:'album',name:'서리 앨범',parentId:null,iconKey:null,colorKey:null,assetCount:3}]};
const suggestions=assetSuggestions([{id:'folder',name:'서리 폴더',parent_id:null,asset_count:1},{id:'character',name:'서리 캐릭터',parent_id:null,asset_count:2,characterNode:'character:c',characterKind:'character'}],undefined,tree,[artist]);
const props={items:suggestions,endpoint:'endpoint',paused:false,onClose:vi.fn(),onChoose:vi.fn()};
beforeEach(()=>{localStorage.clear();mocks.api.mockReset();mocks.api.mockResolvedValue({items:[]});});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.clearAllMocks();vi.useRealTimers();delete (HTMLElement.prototype as unknown as {animate?:unknown}).animate;});
it('groups matching names in folder, character, album, artist order, including initial consonants',()=>{
 const groups=groupAssetSuggestions(suggestions,'ㅅㄹ');
 expect(groups.map(group=>group.label)).toEqual(['폴더','캐릭터','앨범','작가','태그']);
 expect(groups.map(group=>group.items[0]?.id)).toEqual(['folder','character','album','artist',undefined]);
 expect(groupAssetSuggestions(suggestions,'ㅅㄹ ㅍㄷ').flatMap(group=>group.items).map(item=>item.kind)).toEqual(['folder']);
});
it.each(suggestions)('chooses $kind with the existing destination and remembers its identity',item=>{
 render(<AssetSearch {...props}/>);
 fireEvent.change(screen.getByRole('searchbox'),{target:{value:'ㅅㄹ'}});
 fireEvent.click(screen.getByRole('button',{name:new RegExp(item.name)}));
 expect(props.onChoose).toHaveBeenCalledWith(item);
 if(item.kind==='artist')expect(item.artist).toBe(artist);
 else if(item.kind==='album')expect(item.view.album).toEqual({id:'album',libraryId:'library',epoch:3});
 else if(item.kind==='character')expect(item.view.characterNode).toBe('character:c');
 else expect(item.view.classification).toBe('folder');
 expect(readAssetSearchRecents('endpoint')).toEqual([{kind:item.kind,id:item.id}]);
});
it('shows five per group and expands only the selected group with more',()=>{
 const items:AssetSuggestion[]=Array.from({length:7},(_,i)=>({...suggestions[0],id:`folder-${i}`,name:`서리 ${i}`}));
 render(<AssetSearch {...props} items={items}/>);
 fireEvent.change(screen.getByRole('searchbox'),{target:{value:'서리'}});
 expect(document.querySelectorAll('.asset-search-result')).toHaveLength(5);
 fireEvent.click(screen.getByRole('button',{name:'폴더 더 보기'}));
 expect(document.querySelectorAll('.asset-search-result')).toHaveLength(7);
});
it('shows only names while private, hides recents, and never mounts a thumbnail',()=>{
 writeAssetSearchRecents('endpoint',[{kind:'artist',id:'artist'}]);
 localStorage.setItem(PRIVACY_MODE_KEY,'1');
 render(<AssetSearch {...props}/>);
 expect(screen.queryByRole('region',{name:'최근 검색'})).toBeNull();
 fireEvent.change(screen.getByRole('searchbox'),{target:{value:'ㅅㄹ'}});
 const results=document.querySelector('.asset-search-results')!;
 expect(results.querySelector('img,svg,.numeric,.asset-search-cover')).toBeNull();
 expect(results.textContent).toContain('서리 작가');
 act(()=>{localStorage.setItem(PRIVACY_MODE_KEY,'0');window.dispatchEvent(new Event('storage'));});
 expect(results.querySelector('.asset-search-cover')).toBeTruthy();
});
it('keeps eight unique choices newest first, resolves current names, and ignores deleted and other-library items',()=>{
 let history:AssetSearchIdentity[]=[];
 for(let i=0;i<10;i++)history=rememberAssetSearch(history,{kind:'folder',id:`${i}`});
 history=rememberAssetSearch(history,{kind:'folder',id:'5'});
 expect(history).toHaveLength(8);expect(history.map(item=>item.id)).toEqual(['5','9','8','7','6','4','3','2']);
 writeAssetSearchRecents('endpoint',[{kind:'folder',id:'gone'},...suggestions.map(({kind,id})=>({kind,id}))]);
 expect(readAssetSearchRecents('different')).toEqual([]);
 render(<AssetSearch {...props}/>);
 const recent=screen.getByRole('region',{name:'최근 검색'});
 expect(within(recent).getAllByRole('button')).toHaveLength(4);
 expect(within(recent).queryByText('gone')).toBeNull();
 expect(within(recent).getByText('서리 폴더')).toBeTruthy();
});
it('tolerates unavailable or malformed local storage',()=>{
 localStorage.setItem('lakomics.mobile.assetSearch.recents','broken');
 expect(readAssetSearchRecents('endpoint')).toEqual([]);
 vi.spyOn(Storage.prototype,'getItem').mockImplementation(()=>{throw Error('denied');});
 vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw Error('denied');});
 expect(readAssetSearchRecents('endpoint')).toEqual([]);
 expect(()=>writeAssetSearchRecents('endpoint',[])).not.toThrow();
});
it('keeps the same input and results during Korean composition and a delayed list refresh',()=>{
 const view=render(<AssetSearch {...props}/>);
 const input=screen.getByRole('searchbox') as HTMLInputElement;
 fireEvent.change(input,{target:{value:'서리'}});
 const row=screen.getByRole('button',{name:/서리 폴더/});
 fireEvent.compositionStart(input);fireEvent.input(input,{target:{value:'가'},isComposing:true});
 fireEvent.keyDown(input,{key:'Enter',keyCode:13});
 view.rerender(<AssetSearch {...props} loading items={[...suggestions]}/>);
 expect(screen.getByRole('searchbox')).toBe(input);expect(input.value).toBe('가');
 expect(screen.getByRole('button',{name:/서리 폴더/})).toBe(row);
 expect(props.onChoose).not.toHaveBeenCalled();
 fireEvent.compositionEnd(input,{data:'가'});
 expect(screen.queryByRole('button',{name:/서리 폴더/})).toBeNull();
});
it('removes a selected scope through its chip without treating it as a search action',()=>{
 const remove=vi.fn();render(<AssetScopeChips chips={[suggestions[0]]} onRemove={remove}/>);
 fireEvent.click(screen.getByRole('button',{name:'서리 폴더 범위 빼기'}));
 expect(remove).toHaveBeenCalledWith(suggestions[0]);
 expect(assetSearchKey(suggestions[0])).toBe('folder:folder');
});

const tagReply=(id:string,label:string,count=7)=>({items:[{kind:'tag',id,label,count}]});
const advance=async(ms=200)=>{await act(async()=>{await vi.advanceTimersByTimeAsync(ms);});};
it('debounces remote tags, cancels stale reads, retains previous rows, and uses the original tag id',async()=>{
 vi.useFakeTimers();const reads:{path:string;signal:AbortSignal;resolve(value:unknown):void}[]=[];
 mocks.api.mockImplementation((path:string,signal:AbortSignal)=>new Promise(resolve=>reads.push({path,signal,resolve})));
 render(<AssetSearch {...props}/>);const input=screen.getByRole('searchbox');
 fireEvent.change(input,{target:{value:'긴'}});await advance(199);expect(reads).toHaveLength(0);
 fireEvent.change(input,{target:{value:'긴 머리'}});await advance();expect(reads).toHaveLength(1);
 expect(new URL(reads[0].path,'https://test').searchParams.get('text')).toBe('긴 머리');expect(reads[0].path).toContain('limit=10');
 await act(async()=>reads[0].resolve(tagReply('long_hair','긴 머리')));
 const row=within(screen.getByRole('region',{name:'태그'})).getByRole('button',{name:'긴 머리7장'});
 fireEvent.change(input,{target:{value:'안경'}});expect(screen.getByRole('button',{name:'긴 머리7장'})).toBe(row);expect((row as HTMLButtonElement).disabled).toBe(true);
 await advance();expect(reads[0].signal.aborted).toBe(true);
 fireEvent.change(input,{target:{value:'서리'}});expect(reads[1].signal.aborted).toBe(true);await advance();
 await act(async()=>reads[1].resolve(tagReply('glasses','안경')));expect(screen.queryByText('안경')).toBeNull();
 await act(async()=>reads[2].resolve(tagReply('frost','서리 태그',1234)));
 expect(screen.getByRole('region',{name:'폴더'})).toBeTruthy();
 fireEvent.click(screen.getByRole('button',{name:'서리 태그1,234장'}));
 expect(props.onChoose).toHaveBeenCalledWith({kind:'tag',id:'frost',name:'서리 태그',count:1234});
 expect(readAssetSearchRecents('endpoint')).toEqual([{kind:'tag',id:'frost',name:'서리 태그'}]);
});
it('shows a recent tag on reopening, hides all recent choices/counts/covers in privacy mode',async()=>{
 vi.useFakeTimers();writeAssetSearchRecents('endpoint',[{kind:'tag',id:'long_hair',name:'긴 머리'}]);
 const view=render(<AssetSearch {...props}/>);expect(within(screen.getByRole('region',{name:'최근 검색'})).getByText('긴 머리')).toBeTruthy();
 act(()=>{localStorage.setItem(PRIVACY_MODE_KEY,'1');window.dispatchEvent(new Event('storage'));});
 expect(screen.queryByRole('region',{name:'최근 검색'})).toBeNull();
 mocks.api.mockResolvedValue(tagReply('long_hair','긴 머리'));
 fireEvent.change(screen.getByRole('searchbox'),{target:{value:'긴'}});await advance();
 expect(screen.getByRole('region',{name:'태그'}).querySelector('img,svg,.numeric,.asset-search-cover')).toBeNull();
 view.unmount();expect(mocks.api.mock.calls[0][1].aborted).toBe(true);
});
it('keeps local suggestions when offline and quietly clears unavailable tag results',async()=>{
 vi.useFakeTimers();mocks.api.mockResolvedValueOnce(tagReply('frost','서리 태그')).mockRejectedValue(Error('offline'));
 render(<AssetSearch {...props}/>);const input=screen.getByRole('searchbox');
 fireEvent.change(input,{target:{value:'서리'}});await advance();expect(screen.getByRole('region',{name:'태그'})).toBeTruthy();
 fireEvent.change(input,{target:{value:'서리 폴'}});expect(screen.getByRole('region',{name:'태그'})).toBeTruthy();await advance();
 expect(screen.queryByRole('region',{name:'태그'})).toBeNull();expect(screen.getByRole('button',{name:/서리 폴더/})).toBeTruthy();expect(screen.queryByRole('alert')).toBeNull();
});
it('disables a ninth tag and folder with a short hint and keeps Korean composition out of remote requests',async()=>{
 vi.useFakeTimers();const chips=Array.from({length:8},(_,i)=>({kind:'tag' as const,id:String(i),name:String(i)}));
 mocks.api.mockResolvedValue(tagReply('new','새 태그'));
 const view=render(<AssetSearch {...props} chips={chips}/>);const input=screen.getByRole('searchbox');
 fireEvent.compositionStart(input);fireEvent.input(input,{target:{value:'서리'},isComposing:true});await advance();expect(mocks.api).not.toHaveBeenCalled();
 fireEvent.compositionEnd(input,{data:'서리'});await advance();expect(mocks.api).toHaveBeenCalledTimes(1);
 const row=screen.getByRole('button',{name:'새 태그7장'}) as HTMLButtonElement;expect(row.disabled).toBe(true);expect(screen.getByText('태그는 최대 8개입니다.')).toBeTruthy();fireEvent.click(row);expect(props.onChoose).not.toHaveBeenCalled();
 view.rerender(<AssetSearch {...props} chips={chips.map(item=>({...item,kind:'folder'}))}/>);
 expect((screen.getByRole('button',{name:/서리 폴더/}) as HTMLButtonElement).disabled).toBe(true);expect(screen.getByText('폴더는 최대 8개입니다.')).toBeTruthy();
});
it('removes chips independently, offers clear-all for multiple chips, and animates width/opacity for 140 ms',async()=>{
 vi.useFakeTimers();const animations=vi.fn(()=>({cancel:vi.fn(),onfinish:null}));
 Object.defineProperty(HTMLElement.prototype,'animate',{configurable:true,writable:true,value:animations});
 vi.spyOn(Element.prototype,'getBoundingClientRect').mockReturnValue({width:96} as DOMRect);
 const remove=vi.fn(),clear=vi.fn(),tag={kind:'tag' as const,id:'long_hair',name:'긴 머리'};
 const view=render(<AssetScopeChips chips={[suggestions[0],tag]} onRemove={remove} onClear={clear}/>);
 fireEvent.click(screen.getByRole('button',{name:'긴 머리 범위 빼기'}));expect(remove).toHaveBeenCalledWith(tag);
 fireEvent.click(screen.getByRole('button',{name:'모두 지우기'}));expect(clear).toHaveBeenCalledOnce();
 view.rerender(<AssetScopeChips chips={[suggestions[0]]} onRemove={remove} onClear={clear}/>);
 expect(screen.queryByRole('button',{name:'모두 지우기'})).toBeNull();expect(screen.queryByRole('button',{name:'긴 머리 범위 빼기'})).toBeNull();
 expect(animations.mock.calls[0]?.[0]).toEqual([{width:'0px',opacity:0},{width:'96px',opacity:1}]);
 expect(animations.mock.calls.at(-1)?.[1]).toMatchObject({duration:140});expect(animations.mock.calls.at(-1)?.[0]).toEqual([{width:'96px',opacity:1},{width:'0px',opacity:0}]);
 await advance(140);expect(view.container.querySelectorAll('.asset-scope-chip-slot')).toHaveLength(1);
});
