import {act, cleanup, fireEvent, render, screen} from '@testing-library/react';
import {afterEach, beforeEach, expect, it, vi} from 'vitest';
import {ViewerFilmstrip} from './ViewerFilmstrip';
import type {Asset} from './types';
const load = vi.hoisted(() => vi.fn());
vi.mock('./media', () => ({loadThumbnail:load}));
const assets: Asset[] = Array.from({length:100}, (_, i) => ({id:`asset-${i}`,kind:'image',preview:`thumb:${i}`,width:100,height:200}));
beforeEach(() => {vi.stubGlobal('matchMedia', () => ({matches:true}));});
afterEach(() => {cleanup();vi.unstubAllGlobals();vi.clearAllMocks();});
it.each([false, true])('keeps image and video strip geometry identical when grown=%s', grown => {
  const mixed: Asset[] = [assets[0], {...assets[1], kind:'video'}];
  const props = {items:mixed, grown, onIndex:vi.fn()};
  const view = render(<ViewerFilmstrip {...props} index={0}/>);
  const strip = screen.getByRole('navigation');
  const imageClass = strip.className;
  expect(strip.style.getPropertyValue('--filmstrip-height')).toBe('132px');
  expect(strip.classList.contains('is-grown')).toBe(grown);
  view.rerender(<ViewerFilmstrip {...props} index={1}/>);
  expect(strip.className).toBe(imageClass);
  expect(strip.style.getPropertyValue('--filmstrip-height')).toBe('132px');
  expect(strip.style.bottom).toBe('');
});
it('bounds the visible window even after distant navigation', () => {
  const props = {items:assets,onIndex:vi.fn()};
  const view = render(<ViewerFilmstrip {...props} index={50}/>);
  expect(screen.getAllByRole('button').length).toBeLessThan(40);
  view.rerender(<ViewerFilmstrip {...props} index={90}/>);
  expect(screen.getAllByRole('button').length).toBeLessThan(40);
  expect(screen.queryByRole('button',{name:'51번째 자산 보기'})).toBeNull();
  expect(screen.getByRole('button',{name:'91번째 자산 보기'}).getAttribute('aria-current')).toBe('true');
});
it('jumps on a tap and reports touch ownership', () => {
  const onIndex = vi.fn(), onInteractionChange = vi.fn();
  render(<ViewerFilmstrip items={assets} index={50} onIndex={onIndex} onInteractionChange={onInteractionChange}/>);
  const button = screen.getByRole('button',{name:'52번째 자산 보기'});
  fireEvent.pointerDown(button,{pointerId:1,clientX:100,clientY:20});
  fireEvent.pointerUp(button,{pointerId:1,clientX:100,clientY:20});
  fireEvent.click(button);
  expect(onIndex).toHaveBeenCalledWith(51);
  expect(onInteractionChange.mock.calls).toEqual([[true],[false]]);
});
it('accepts upward swipes on the bottom strip and includes video neighbours', () => {
  const onSwipeUp = vi.fn();
  render(<ViewerFilmstrip items={[{...assets[0],kind:'video'},assets[1]]} index={0} onIndex={()=>{}} onSwipeUp={onSwipeUp}/>);
  const strip=screen.getByRole('navigation');
  fireEvent.pointerDown(strip,{pointerId:1,clientX:100,clientY:100});
  fireEvent.pointerMove(strip,{pointerId:1,clientX:100,clientY:20});
  fireEvent.pointerUp(strip,{pointerId:1,clientX:100,clientY:20});
  expect(onSwipeUp).toHaveBeenCalledOnce();
});
it('reuses loaded thumbnails when virtual items remount', async () => {
  load.mockResolvedValue({preview:'cached:unique'});
  const many=assets.map((asset,i)=>({...asset,id:`cached-${i}`,preview:undefined}));
  const props={items:many,onIndex:()=>{}};
  const view=render(<ViewerFilmstrip {...props} index={50}/>);
  await act(async()=>{await Promise.resolve();});
  const count=load.mock.calls.filter(([asset])=>asset.id==='cached-50').length;
  view.rerender(<ViewerFilmstrip {...props} index={90}/>);
  await act(async()=>{await Promise.resolve();});
  view.rerender(<ViewerFilmstrip {...props} index={50}/>);
  expect(load.mock.calls.filter(([asset])=>asset.id==='cached-50')).toHaveLength(count);
});
