package com.lakomics.cloudpoc;
import android.content.ContentResolver;
import android.content.res.AssetFileDescriptor;
import android.database.MatrixCursor;
import android.graphics.Point;
import android.os.*;
import android.provider.CloudMediaProvider;
import android.provider.CloudMediaProviderContract;
import org.json.*;
import java.io.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
public final class CloudAlbumProvider extends CloudMediaProvider {
 private JSONObject config; private String collection; private long generation;
 public boolean onCreate(){return true;}
 private synchronized void load(){load(false);}
 private synchronized void load(boolean refresh){try{config=AlbumSync.load(getContext(),refresh);collection="lakomics-albums-"+config.getString("revision");generation=config.getLong("generation");}catch(Exception e){throw new IllegalStateException("Album connection unavailable");}}

 public Bundle onGetMediaCollectionInfo(Bundle extras){load(true);Bundle b=new Bundle();b.putString("media_collection_id",collection);b.putLong("last_media_sync_generation",generation);b.putString("account_name","Lakomics");return b;}
 private void attach(MatrixCursor c,String... args){Bundle b=new Bundle();b.putString(CloudMediaProviderContract.EXTRA_MEDIA_COLLECTION_ID,collection);b.putStringArrayList(ContentResolver.EXTRA_HONORED_ARGS,new ArrayList<String>(Arrays.asList(args)));c.setExtras(b);}
 private boolean member(JSONObject m,String id){JSONArray a=m.optJSONArray("albums");for(int i=0;i<a.length();i++)if(id.equals(a.optString(i)))return true;return false;}
 public MatrixCursor onQueryMedia(Bundle extras){load();MatrixCursor c=new MatrixCursor(new String[]{"id","date_taken_millis","sync_generation","mime_type","standard_mime_type_extension","size_bytes","duration_millis","is_favorite","width","height","orientation"});String album=extras==null?null:extras.getString(CloudMediaProviderContract.EXTRA_ALBUM_ID);long after=extras==null?-1:extras.getLong(CloudMediaProviderContract.EXTRA_SYNC_GENERATION,-1);JSONArray media=config.optJSONArray("media");for(int i=0;i<media.length();i++){JSONObject m=media.optJSONObject(i);if(after>=generation||(album!=null&&!member(m,album)))continue;c.addRow(new Object[]{m.optString("id"),m.optLong("date"),generation,m.optString("mime"),0,m.optLong("size"),m.optLong("duration"),0,m.optInt("width"),m.optInt("height"),0});}ArrayList<String> args=new ArrayList<>();if(album!=null)args.add(CloudMediaProviderContract.EXTRA_ALBUM_ID);if(extras!=null&&extras.containsKey(CloudMediaProviderContract.EXTRA_SYNC_GENERATION))args.add(CloudMediaProviderContract.EXTRA_SYNC_GENERATION);attach(c,args.toArray(new String[0]));return c;}
 public MatrixCursor onQueryDeletedMedia(Bundle extras){load();MatrixCursor c=new MatrixCursor(new String[]{"id"});attach(c,CloudMediaProviderContract.EXTRA_SYNC_GENERATION);return c;}
 public MatrixCursor onQueryAlbums(Bundle extras){load();MatrixCursor c=new MatrixCursor(new String[]{"id","date_taken_millis","display_name",CloudMediaProviderContract.AlbumColumns.MEDIA_COVER_ID,CloudMediaProviderContract.AlbumColumns.MEDIA_COUNT});JSONArray albums=config.optJSONArray("albums"),media=config.optJSONArray("media");for(int i=0;i<albums.length();i++){JSONObject a=albums.optJSONObject(i);String cover=null;long count=0,date=0;for(int j=0;j<media.length();j++){JSONObject m=media.optJSONObject(j);if(!member(m,a.optString("id")))continue;count++;if(cover==null)cover=m.optString("id");date=Math.max(date,m.optLong("date"));}if(count==0)continue;c.addRow(new Object[]{a.optString("id"),date,a.optString("name"),cover,count});}attach(c);return c;}
 public ParcelFileDescriptor onOpenMedia(String id,Bundle extras,CancellationSignal signal)throws FileNotFoundException{return ParcelFileDescriptor.open(fetch(id,"original",signal),ParcelFileDescriptor.MODE_READ_ONLY);}
 public AssetFileDescriptor onOpenPreview(String id,Point size,Bundle extras,CancellationSignal signal)throws FileNotFoundException{File f=fetch(id,"thumbnail",signal);return new AssetFileDescriptor(ParcelFileDescriptor.open(f,ParcelFileDescriptor.MODE_READ_ONLY),0,f.length());}
 private synchronized File fetch(String id,String variant,CancellationSignal signal)throws FileNotFoundException{load();JSONObject target=null;JSONArray media=config.optJSONArray("media");for(int i=0;i<media.length();i++)if(id.equals(media.optJSONObject(i).optString("id")))target=media.optJSONObject(i);if(target==null||!id.matches("[a-zA-Z0-9-]+"))throw new FileNotFoundException("Unknown media");File file=new File(getContext().getCacheDir(),id+"-"+variant);if(signal!=null)signal.throwIfCanceled();if(file.exists()&&file.length()>0)return file;File pending=new File(file.getPath()+".part");HttpURLConnection api=null,remote=null;try{api=connect(config.getString("base")+"/v1/library/assets/"+id+"/media-ticket");api.setRequestMethod("POST");api.setDoOutput(true);api.setRequestProperty("Authorization","Bearer "+config.getString("token"));api.setRequestProperty("Content-Type","application/json");try(OutputStream out=api.getOutputStream()){out.write(("{\"variant\":\""+variant+"\"}").getBytes(StandardCharsets.UTF_8));}if(api.getResponseCode()!=200)throw new IOException();JSONObject ticket;try(InputStream in=api.getInputStream()){ticket=new JSONObject(new String(read(in,65536,signal),StandardCharsets.UTF_8));}remote=connect(ticket.getString("url"));final HttpURLConnection activeRemote=remote;if(signal!=null)signal.setOnCancelListener(new CancellationSignal.OnCancelListener(){public void onCancel(){activeRemote.disconnect();}});if(remote.getResponseCode()!=200)throw new IOException();long limit=variant.equals("thumbnail")?8388608:Math.max(1,target.getLong("size"));long total=0;try(InputStream in=remote.getInputStream();OutputStream out=new FileOutputStream(pending)){byte[] buffer=new byte[32768];int n;while((n=in.read(buffer))!=-1){if(signal!=null)signal.throwIfCanceled();total+=n;if(total>limit)throw new IOException();out.write(buffer,0,n);}}if(total==0||(!variant.equals("thumbnail")&&total!=target.getLong("size")))throw new IOException();if(!pending.renameTo(file))throw new IOException();android.util.Log.i("LakomicsCMP","Cloud fetch complete variant="+variant+" bytes="+total);return file;}catch(Exception e){pending.delete();throw new FileNotFoundException("Cloud media could not be loaded");}finally{if(signal!=null)signal.setOnCancelListener(null);if(api!=null)api.disconnect();if(remote!=null)remote.disconnect();}}
 private HttpURLConnection connect(String value)throws IOException{URL u=new URL(value);if(!u.getProtocol().equals("https")){String[] parts=u.getHost().split("\\.");boolean tailscale=parts.length==4&&parts[0].equals("100")&&Integer.parseInt(parts[1])>=64&&Integer.parseInt(parts[1])<=127;if(!u.getProtocol().equals("http")||!tailscale||!value.startsWith(config.optString("base")+"/v1/library/"))throw new IOException();}HttpURLConnection c=(HttpURLConnection)u.openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(30000);return c;}
 private static byte[] read(InputStream in,int limit,CancellationSignal s)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(s!=null)s.throwIfCanceled();if(out.size()+n>limit)throw new IOException();out.write(b,0,n);}return out.toByteArray();}
}
